incorporating scene manager to the most updated version
nmarhari/SWE-Alpha pull request #41
Opened 2024-03-02 17:48 UTC by HadjAhmed2003

2024-03-03 23:44 UTC, nmarhari commented
Can no longer use mouse to move

2024-03-04 00:33 UTC, nmarhari requested changes
can no longer use  mouse to move, the main way to interact with the game

2024-03-04 00:35 UTC, brandonscholten approved these changes

2024-03-04 00:36 UTC, brandonscholten commented
Until this mouse works using scene manager we have decided it is best not to merge with the production branch.

2024-03-10 22:47 UTC, closed without merging